name: Update Bot
on:
  schedule:
    - cron: '*/5 * * * *' # This tells GitHub to run every 5 minutes
  workflow_dispatch: # This adds a button so you can start it manually
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_MESSAGE_ID: ${{ secrets.DISCORD_MESSAGE_ID }}
