name: Update Bot

on:
  schedule:
 on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '2-59/5 * * * *' # Offset by 2 minutes
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_MESSAGE_ID: ${{ secrets.DISCORD_MESSAGE_ID }}
